id: P000548
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:46:13.223174
source_metadata:
  id: bdr:W21782
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    057a4299875547999edee8a88d2e6fa6:
      image_group_id: I1KG23247
      title: Volume 1 of gzhon nu drug gi rtogs brjod/
      volume_number: 1
      total_pages: 108
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
